import { PrismaClient } from '@prisma/client';
export declare function seedAuth(prisma: PrismaClient): Promise<{
  admin: {
    name: string | null;
    id: string;
    updatedAt: Date;
    createdAt: Date;
    status: import('@prisma/client').$Enums.UserStatus;
    email: string;
    password: string;
    role: import('@prisma/client').$Enums.UserRole;
    credits: number;
    stripeCustomerId: string | null;
    emailVerified: Date | null;
    image: string | null;
    autoRecalculateMacros: boolean;
    healthLastSync: Date | null;
    healthPlatform: string | null;
    betaEnabled: boolean;
    invitationId: string | null;
    copilotEnabled: boolean;
  } | null;
  demoUser: {
    name: string | null;
    id: string;
    updatedAt: Date;
    createdAt: Date;
    status: import('@prisma/client').$Enums.UserStatus;
    email: string;
    password: string;
    role: import('@prisma/client').$Enums.UserRole;
    credits: number;
    stripeCustomerId: string | null;
    emailVerified: Date | null;
    image: string | null;
    autoRecalculateMacros: boolean;
    healthLastSync: Date | null;
    healthPlatform: string | null;
    betaEnabled: boolean;
    invitationId: string | null;
    copilotEnabled: boolean;
  } | null;
}>;
